version: '3.9'

services:
  frontend:
    image: dada0013/frontend:latest 
    ports:
      - "80:80"  # 호스트의 80번 포트와 컨테이너의 80번 포트를 연결
    networks:
      - my_app_network  # 컨테이너 간 통신을 위한 네트워크 지정
    depends_on:
      - backend  # 프론트엔드는 백엔드 서비스에 의존
    deploy:
      placement:
        constraints:
          - node.hostname == worker1

  backend:
    image: dada0013/backend:latest  # 백엔드 이미지 이름
    ports:
      - "5000:5000"  # 호스트의 5000번 포트와 컨테이너의 5000번 포트를 연결
    networks:
      - my_app_network  # 컨테이너 간 통신을 위한 네트워크 지정
    depends_on:
      - mongodb  # 백엔드는 MongoDB 서비스에 의존
    deploy:
      placement:
        constraints:
          - node.hostname == worker2
  mongodb:
    image: mongo
    networks:
      - my_app_network  # 컨테이너 간 통신을 위한 네트워크 지정
    volumes:
      - mongodb_data:/data/db  # 데이터를 유지하기 위한 볼륨 설정
    deploy:
      placement:
        constraints:
          - node.hostname == worker3
volumes:
  mongodb_data: 

networks:
  my_app_network:  # 컨테이너 간 통신을 위한 사용자 정의 네트워크 생성
    driver: overlay

