version: '3.9'

services:
  frontend:
    image: dada0013/frontend:latest
    ports:
      - "8081:80"
    networks:
      - my_app_network
    depends_on:
      - backend
    deploy:
      placement:
        constraints:
          - node.hostname == worker1

  backend:
    image: dada0013/backend:latest
    ports:
      - "5001:5000"
    networks:
      - my_app_network
    depends_on:
      - mongodb1
      - mongodb2
    deploy:
      placement:
        constraints:
          - node.hostname == worker2

  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    command: mongod --replSet rs0 --bind_ip_all
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb1_data:/data/db  # 볼륨 이름을 mongodb1_data로 변경
    deploy:
      placement:
        constraints:
          - node.hostname == worker3

  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    command: mongod --replSet rs0 --bind_ip_all
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb2_data:/data/db  # 볼륨 이름을 mongodb2_data로 변경
    deploy:
      placement:
        constraints:
          - node.hostname == worker3

volumes:
  mongodb1_data:
  mongodb2_data:

networks:
  my_app_network:
    driver: overlay
    attachable: true
